import Head from "next/head";
import Card from "../components/Card/Card";
import Test from "../components/Test/Test";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <Card />
        {/* <Test /> */}
      </div>
    </div>
  );
}
